services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --config /etc/cloudflared/tunnel/config.yml run
    volumes:
      - ./tunnels/providers/cloudflare:/etc/cloudflared/tunnel:ro
      - ${HOME}/.cloudflared/${TUNNEL_ID}.json:/etc/cloudflared/credentials.json:ro
    dns:
      - 172.17.0.1
    networks:
      - webserver
    mem_limit: 256m
    restart: unless-stopped
    depends_on:
      dokku:
        condition: service_started

  dokku:
    image: dokku/dokku:0.37.7
    container_name: dokku
    hostname: ${DOKKU_HOSTNAME:-apps.local}
    environment:
      DOKKU_HOSTNAME: ${DOKKU_HOSTNAME:-apps.local}
      DOKKU_HOST_ROOT: /var/lib/dokku/home/dokku
      DOKKU_LIB_HOST_ROOT: /var/lib/dokku/var/lib/dokku
    ports:
      - "3022:22"
    volumes:
      - dokku-data:/mnt/dokku
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 172.17.0.1
    pid: host
    mem_limit: 256m
    networks:
      - webserver
    restart: unless-stopped

networks:
  webserver:
    external: true

volumes:
  dokku-data:
    external: true
